[package]
name = "MyManor.esp"
authors = ["JosephMcKean"]
version = "1.0.0"

[dependencies]
assets = [
    "Icons/jsmk/fc/",
    "Meshes/jsmk/fc/",
    "MWSE/mods/JosephMcKean/MyManor",
    "Textures/jsmk/fc",
]

[dependencies.mwse]
buildnumber = 3247