name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install zip
        run: sudo apt-get update -y && sudo apt-get install zip -y
      - name: Create Zip File
        run: |
          ZIP_FILE="${GITHUB_REPOSITORY##*/}-${GITHUB_REF_NAME}.zip"
          echo "ZIP_FILE=${ZIP_FILE}" >> $GITHUB_ENV
          find . -type f ! -path '*/.*' ! -path './dev/*' | zip $ZIP_FILE -@
        id: zip_creation
      
      - name: Set Zip Path Output
        id: zip_output
        run: echo "::set-output name=zip-path::${{ env.ZIP_FILE }}"
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: project-zip
          path: ${{ env.ZIP_FILE }}

  release:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: project-zip
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./${{ needs.package.outputs.zip-path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}